version: '3.8'

services:
  app:
    build: .
    container_name: cybershop_app
    ports:
      - "8848:8848" # Port 80 boshqa sayt tomonidan band bo'lmasligi uchun 8848-portga o'zgardi
    depends_on:
      - db
    restart: always
    volumes:
      - ./config.prod.json:/app/config.json
      - ./uploads:/app/uploads

  db:
    image: postgres:15
    container_name: cybershop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hojiakbar
      POSTGRES_DB: jobeasy_db
    # ports:
    #   - "5432:5432" # Serverdagi boshqa ma'lumotlar bazalariga xalaqit bermasligi uchun yopildi
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./upgrade_v2.sql:/docker-entrypoint-initdb.d/2_upgrade_v2.sql
    restart: always

volumes:
  pgdata:
